In [469]:
import random
import numpy as np
arr = np.random.randint(1,50,(5,4))
print(arr)
print(arr[0][3] , arr[1][2] , arr[2][1] , arr[3][0])

[[45 40 43 30]
 [45 28 40 29]
 [19  2 42  3]
 [14 48 48 47]
 [ 2 14 43 22]]
30 40 2 14


In [470]:
print(np.max(arr,axis = 1))

[45 45 42 48 43]


In [471]:
mean = np.mean(arr)
arr1 = arr[arr <= mean]
arr1

array([30, 28, 29, 19,  2,  3, 14,  2, 14, 22])

In [472]:
import numpy as np

def numpy_boundary_transversal(matrix):
    ans = []
    top, bottom = 0, matrix.shape[0] - 1
    left, right = 0, matrix.shape[1] - 1

    while top <= bottom and left <= right:
        for j in range(left, right + 1):
            ans.append(matrix[top][j])
        top += 1

        for i in range(top, bottom + 1):
            ans.append(matrix[i][right])
        right -= 1

        if top <= bottom:
            for j in range(right, left - 1, -1):
                ans.append(matrix[bottom][j])
            bottom -= 1

        if left <= right:
            for i in range(bottom, top - 1, -1):
                ans.append(matrix[i][left])
            left += 1

    return ans

print(numpy_boundary_transversal(arr))

[45, 40, 43, 30, 29, 3, 47, 22, 43, 14, 2, 14, 19, 45, 28, 40, 42, 48, 48, 2]


In [473]:
#PROBLEM 2
arr2 = np.random.rand(20)
print(arr2*10)

[8.26864764 4.74434756 6.28755211 5.022962   5.90024011 4.7147089
 8.28932274 3.84491207 9.34856665 0.15755423 8.77550143 5.42434232
 9.98597328 5.74416675 8.21696558 2.85436285 0.08804142 7.55546944
 7.51561123 4.62402566]


In [474]:
print(np.min(arr2*10))

0.08804141785772712


In [475]:
print(np.max(arr2*10))
print(np.median(arr2*10))

9.985973282535056
5.822203430293399


In [476]:
arr3 = arr2*10
arr3 = np.where(arr3 >= 5, arr3, (arr3) * (arr3))
arr3

array([8.26864764e+00, 2.25088337e+01, 6.28755211e+00, 5.02296200e+00,
       5.90024011e+00, 2.22284801e+01, 8.28932274e+00, 1.47833488e+01,
       9.34856665e+00, 2.48233338e-02, 8.77550143e+00, 5.42434232e+00,
       9.98597328e+00, 5.74416675e+00, 8.21696558e+00, 8.14738728e+00,
       7.75129126e-03, 7.55546944e+00, 7.51561123e+00, 2.13816133e+01])

In [477]:
def numpy_alternate_sort(arr):
    sort_arr = np.sort(arr)
    result = []
    left = 0 
    right = len(arr) - 1
    while(left <= right):
        result.append(sort_arr[left])
        result.append(sort_arr[right])
        left += 1
        right -= 1

    return np.array(result)

x = [6,9,2,4,7,3]
print(numpy_alternate_sort(x))

[2 9 3 7 4 6]


In [478]:
#Q.3
import pandas as pd
df = pd.DataFrame()
df['Name'] = ['A','B','C','D','E','F','G','H','I','J']
df['Subject'] = ['MA','CS','CE','CE','MA','MA','CS','CE','CS','MA']
df['Score'] = np.random.randint(50,101,10)
df['Grade'] = None
print(df)
for i , score in enumerate(df['Score']):
    if(score >= 90):
        df.loc[i,'Grade'] = 'A'
    elif(score >= 80):
        df.loc[i,'Grade'] = 'B'
    elif(score >= 70):
        df.loc[i,'Grade'] = 'C'
    elif(score >= 60):
        df.loc[i,'Grade'] = 'D'
    else:
        df.loc[i,'Grade'] = 'F'

print(df)
new_df = df.groupby('Subject')
print(new_df['Score'].mean())

  Name Subject  Score Grade
0    A      MA     75  None
1    B      CS     88  None
2    C      CE     67  None
3    D      CE     79  None
4    E      MA     72  None
5    F      MA     98  None
6    G      CS     69  None
7    H      CE     63  None
8    I      CS     67  None
9    J      MA     72  None
  Name Subject  Score Grade
0    A      MA     75     C
1    B      CS     88     B
2    C      CE     67     D
3    D      CE     79     C
4    E      MA     72     C
5    F      MA     98     A
6    G      CS     69     D
7    H      CE     63     D
8    I      CS     67     D
9    J      MA     72     C
Subject
CE    69.666667
CS    74.666667
MA    79.250000
Name: Score, dtype: float64


In [479]:
def pandas_filter_pass(dataframe):
    df1 = df[(df['Grade'] == 'A') | (df['Grade'] == 'B')]
    return df1 

print(pandas_filter_pass(df))

  Name Subject  Score Grade
1    B      CS     88     B
5    F      MA     98     A


In [480]:
#Q.4
positive_reviews = [
    "An absolute masterpiece from start to finish.",
    "The acting was phenomenal, especially the lead.",
    "I was smiling throughout the movie.",
    "Brilliant plot and excellent direction.",
    "This film restored my faith in cinema.",
    "A perfect blend of action and emotion.",
    "One of the best movies I’ve seen this year.",
    "The cinematography was breathtaking.",
    "A must-watch for everyone.",
    "It exceeded all my expectations.",
    "Heartwarming and beautifully shot.",
    "The script was clever and engaging.",
    "Left me inspired and full of joy.",
    "A cinematic triumph.",
    "Every moment was pure gold.",
    "I could watch it again and again.",
    "The soundtrack was unforgettable.",
    "Top-notch storytelling!",
    "The emotional depth was incredible.",
    "The director did a fantastic job.",
    "Absolutely loved it!",
    "Flawless in every way.",
    "Characters were well-developed.",
    "The plot twists were mind-blowing.",
    "Oscar-worthy performances.",
    "Such a satisfying ending.",
    "Great balance of humor and drama.",
    "Visually stunning from start to end.",
    "Left the theater with a smile.",
    "Exceeded even the hype.",
    "Genuinely touching.",
    "Completely absorbing.",
    "A delightful experience.",
    "Pure entertainment.",
    "Packed with memorable moments.",
    "A true gem.",
    "It had me hooked from the first scene.",
    "Smart, funny, and heartfelt.",
    "A refreshing take on the genre.",
    "Hands down, a great film.",
    "Would recommend to everyone.",
    "Just wow. Absolutely brilliant.",
    "Deserves all the praise it's getting.",
    "A five-star experience.",
    "Blew me away.",
    "Impressive performances all around.",
    "Every scene was crafted with care.",
    "Such a beautiful story.",
    "A modern classic.",
    "Loved every second."
]

negative_reviews = [
    "A complete waste of time.",
    "The acting was wooden and lifeless.",
    "I struggled to stay awake.",
    "The plot made no sense at all.",
    "Terribly executed.",
    "One of the worst movies I’ve ever seen.",
    "The dialogue was cringeworthy.",
    "Painfully slow and boring.",
    "I regret watching it.",
    "Couldn't finish it.",
    "What were they thinking?",
    "The story was a mess.",
    "Horrible pacing.",
    "It lacked everything a good movie should have.",
    "Bad acting and worse writing.",
    "A disappointment in every way.",
    "Totally unwatchable.",
    "I want my two hours back.",
    "Cliché after cliché.",
    "Sounded like it was written by a child.",
    "Characters were flat and forgettable.",
    "So bad, it’s funny.",
    "Complete garbage.",
    "Why did they even make this?",
    "I wouldn’t recommend it to anyone.",
    "Uninspired and dull.",
    "The ending made no sense.",
    "Awful special effects.",
    "Zero emotional impact.",
    "Truly pathetic effort.",
    "Insult to the audience’s intelligence.",
    "This film is a disaster.",
    "Fell completely flat.",
    "The jokes didn’t land.",
    "It was just noise and chaos.",
    "Forgettable in every way.",
    "Poorly directed and poorly acted.",
    "I expected more, got so much less.",
    "Nothing redeemable here.",
    "Even the trailer was misleading.",
    "Absolute flop.",
    "Left the theater annoyed.",
    "Predictable and dry.",
    "The hype was totally undeserved.",
    "Embarrassing to watch.",
    "Just bad, plain and simple.",
    "Terrible on every level.",
    "Would not recommend.",
    "A frustrating experience.",
    "Cringed all the way through."
]

all_reviews = list(zip(positive_reviews, [1]*50)) + list(zip(negative_reviews, [0]*50))
random.shuffle(all_reviews)

nlp_df = pd.DataFrame(all_reviews, columns=['Review', 'Sentiment'])
nlp_df

Review  Sentiment
0                   Every moment was pure gold.          1
1                          Totally unwatchable.          0
2   One of the best movies I’ve seen this year.          1
3            I expected more, got so much less.          0
4                      What were they thinking?          0
..                                          ...        ...
95                           Terribly executed.          0
96       Insult to the audience’s intelligence.          0
97           I wouldn’t recommend it to anyone.          0
98           The plot twists were mind-blowing.          1
99                         Uninspired and dull.          0

[100 rows x 2 columns]

In [481]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 500 , stop_words = 'english', ngram_range = (1,2))

bow = cv.fit_transform(nlp_df['Review'])
print(bow[0].toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [482]:
from sklearn.model_selection import train_test_split
y = nlp_df['Sentiment']
X_train , X_test , y_train , y_test = train_test_split(bow,y,test_size = 0.2, random_state = 23)

In [483]:
X_train.shape

(80, 353)

In [484]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
accuracy = accuracy*100
print(f"Test Accuracy: {accuracy:.2f}")

Test Accuracy: 65.00


In [485]:
def predict_review_sentiment(modl,vectorizer,review):
    x = vectorizer.transform([review])
    pred = modl.predict(x)
    return pred

print(predict_review_sentiment(model,cv,nlp_df['Review'][0]))
print(nlp_df['Sentiment'][0])

[1]
1


In [486]:
#Q.5
good_feedback = [
    "Loved the product!",
    "Excellent quality and fast delivery.",
    "Highly recommend this item.",
    "Very satisfied with my purchase.",
    "Works perfectly as expected.",
    "Amazing value for the price.",
    "The product exceeded my expectations.",
    "Five stars, will buy again!",
    "Smooth and easy experience.",
    "The material feels premium.",
    "Product arrived in great condition.",
    "Very useful and well-designed.",
    "Definitely worth the money.",
    "The packaging was top-notch.",
    "It works like a charm.",
    "Looks exactly like the pictures.",
    "Fits perfectly and looks great.",
    "Great support from the seller.",
    "This is my second time buying it.",
    "I’m impressed with the performance.",
    "Reliable and efficient product.",
    "It’s become part of my daily routine.",
    "Couldn’t be happier with this.",
    "A pleasant surprise overall.",
    "The battery lasts really long.",
    "Build quality is excellent.",
    "Would absolutely recommend to friends.",
    "Everything about it is perfect.",
    "Simple yet very effective.",
    "Great for everyday use.",
    "Met all my expectations.",
    "Nice finish and detailing.",
    "Easy to set up and use.",
    "Great value for money.",
    "Very comfortable to use.",
    "Product is exactly as described.",
    "Nice color and texture.",
    "Super fast shipping.",
    "I use it daily now.",
    "Feels durable and strong.",
    "Perfect gift for anyone.",
    "Extremely satisfied with this.",
    "Better than other brands.",
    "Performs well under heavy use.",
    "Truly a must-have item.",
    "No complaints at all.",
    "Efficient and well-built.",
    "This was a great buy.",
    "Totally worth the price.",
    "Feels like a premium product."
]

bad_feedback = [
    "Terrible experience overall.",
    "The product broke after one use.",
    "Not worth the money.",
    "Very disappointed with the quality.",
    "Did not match the description.",
    "Late delivery and poor packaging.",
    "Stopped working within a week.",
    "Waste of money.",
    "I regret buying this.",
    "Would not recommend to anyone.",
    "Feels cheap and flimsy.",
    "The size was completely wrong.",
    "Color faded after first wash.",
    "Seller was unresponsive.",
    "Not satisfied at all.",
    "Item arrived damaged.",
    "Doesn't work as advertised.",
    "Too expensive for what it offers.",
    "Not as good as expected.",
    "Bad build quality.",
    "Very uncomfortable to use.",
    "Already looking for a replacement.",
    "Worst product I’ve bought.",
    "Returned it immediately.",
    "No support from seller.",
    "Looks nothing like the pictures.",
    "The instructions were unclear.",
    "Installation was a nightmare.",
    "It’s very noisy and annoying.",
    "Did not meet expectations.",
    "Battery life is terrible.",
    "Not durable at all.",
    "Totally useless.",
    "Feels like a scam.",
    "Poor quality control.",
    "Don’t waste your money.",
    "Wrong item delivered.",
    "Looks cheap and fragile.",
    "It was a huge letdown.",
    "Barely works properly.",
    "Doesn’t serve the purpose.",
    "Performance is below average.",
    "Misleading product listing.",
    "It heats up quickly.",
    "Feels like second-hand.",
    "Packaging was torn.",
    "Stopped charging after 2 days.",
    "Disappointed beyond words.",
    "Shipping took forever.",
    "Doesn’t fit at all."
]

dataset = list(zip(good_feedback, [1]*50)) + list(zip(bad_feedback, [0]*50))
random.shuffle(dataset)

q5_df = pd.DataFrame(dataset,columns = ['Review','Sentiment'])
q5_df

Review  Sentiment
0                      Totally useless.          0
1        Stopped working within a week.          0
2        Extremely satisfied with this.          1
3                 I regret buying this.          0
4              Perfect gift for anyone.          1
..                                  ...        ...
95  Very disappointed with the quality.          0
96        It’s very noisy and annoying.          0
97   Already looking for a replacement.          0
98               Shipping took forever.          0
99             Seller was unresponsive.          0

[100 rows x 2 columns]

In [487]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 300, stop_words = 'english',lowercase = True,  ngram_range=(1,3))
X1 = tfidf.fit_transform(q5_df['Review'])
y1 = q5_df['Sentiment']

X_train1 , X_test1 , y_train1 , y_test1 = train_test_split(X1,y1,test_size = 0.25, random_state = 3)
X_train.shape

(80, 353)

In [488]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score , accuracy_score

model = LogisticRegression()
model.fit(X_train1, y_train1)

y_pred1 = model.predict(X_test1)

precision = precision_score(y_test1, y_pred1)
recall = recall_score(y_test1, y_pred1)
f1 = f1_score(y_test1, y_pred1)

print(f"Precision: {precision:.2f}")
print(f"Recall:    {recall:.2f}")
print(f"F1 Score:  {f1:.2f}")

accuracy = accuracy_score(y_test1, y_pred1)
accuracy = accuracy*100
print(f"Test Accuracy: {accuracy:.2f}")

Precision: 0.75
Recall:    0.20
F1 Score:  0.32
Test Accuracy: 48.00
